- name: Install packages
  community.general.pacman:
    name:
      - base-devel
      - bat
      - fd
      - fzf
      - git
      - htop
      - iotop
      - lm_sensors
      - man-db
      - man-pages
      - p7zip
      - pacman-contrib
      - plocate
      - ripgrep
      - smartmontools
      - sudo
      - zsh
      - vi
      - vim
    state: present
    update_cache: true
- name: ensure plocate-updatedb.timer is enabled
  ansible.builtin.systemd:
    name: plocate-updatedb.timer
    state: started
    enabled: yes
- name: symlink vim to vi
  ansible.builtin.file:
    src: /usr/bin/vim
    dest: /usr/bin/vi
    state: link
- name: scripts directory
  ansible.builtin.file:
    path: /root/scripts
    state: directory
    owner: root
    group: root
    mode: "755"
- name: update pacman mirrors script
  ansible.builtin.copy:
    src: files/pacman-new-mirrorlist.sh
    dest: /root/scripts/pacman-new-mirrorlist.sh
    owner: root
    group: root
    mode: "700"
